name: Release

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Issue Description
        run: |
          REPO_URL="https://github.com/danreeves/darktide-mods"
          FOLDERS=$(find . -maxdepth 1 -type d ! -name '.*' -exec basename {} \; | while read folder; do
            MOD_DATE=$(find "$folder" -type f -exec stat -c '%Y' {} + | sort -nr | head -n 1 | xargs -I{} date -d @{} '+%Y-%m-%d')
            echo "- [Download ${folder}](https://download-directory.github.io/?url=${REPO_URL}/tree/main/${folder}&filename=${folder}) (Last modified: ${MOD_DATE})"
          done)
          gh issue edit 107 --body "$(cat <<EOF
          # Download the latest releases before they hit Nexus
          These links will open an external website and and will automatically download the latest zip.
          These are pre-release versions and may contain bugs or unfinished features. It's recommended to use the Nexus releases for a more stable experience.
          [My Nexus Mods](https://next.nexusmods.com/profile/dnrvs/mods)

          $FOLDERS

          Last updated: $(date '+%Y-%m-%d %H:%M:%S')
          EOF
          )"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
