name: Release

on: 
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Zip
        uses: montudor/action-zip@v1
      - name: Zip each directory
        run: |
          for dir in */; do
          zip -qq -r "${dir%/}.zip" "$dir"
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.zip"
